bowtie:
    ignore-quals: ['True', '--']
    local: ['True', '--']
    very-sensitive-local: ['True', '--']
    rfg: ['9,5', '--']
    rdg: ['9,5', '--']
    score-min: ['L,20,1.4', '--'] 
    k: ['8', '-']
    no-unal: ['True', '--']
    no-mixed: ['True', '--']
    p: ['8', '--']
    I: ['40', '-']
    X: ['800', '-']
peak_detection:
    widthfactor: 0.9
    meanmult: 4.0
peak_filtering_loose:
    zscore: 2.0
    minmedian: 1.0
peak_filtering_normal:
    zscore: 3.0
    minmedian: 2.0
peak_filtering_strict:
    zscore: 5.0
    minmedian: 2.5
coverage:
    zscore: 2.0
    mode: 'noise'
    trackopts: 
        color: '60,150,237'
        type: 'bedGraph'
        visibility: '2'
    multiplier: 100
annotation:
    maxshift: 50
    flen: 50
region:
    flank: 40
    zscore: 5
    min-zscore: 2
    maxshift: 40
control:
    smooth: 500
